- name: Ejemplos windows
  hosts: all
  tasks:
#  - name: Run a command under PowerShell
#    win_shell: Get-Service -Name service | Stop-Service
  - name: Run a command under cmd
    win_shell: mkdir C:\temp11
    args:
      executable: cmd.exe

  - name: Run a multiple shell commands
    win_shell: |
      New-Item -Path C:\temp21 -ItemType Directory
      Remove-Item -Path C:\temp21 -Force -Recurse
      $path_info = Get-Item -Path C:\temp21
      $path_info.FullName

  - name: Run an executable using win_command
    win_command: whoami.exe
  
  # - name: Run a cmd command
  #   win_command: cmd.exe /c mkdir C:\temp